INSERT INTO APP.CLINIC_USER_EXPERTISE (VET_CLINIC_USER_ID, EXPERTISES_EXPERTISE_ID)
VALUES ('1901', '13');
INSERT INTO APP.CLINIC_USER_EXPERTISE (VET_CLINIC_USER_ID, EXPERTISES_EXPERTISE_ID)
VALUES ('1901', '4');
INSERT INTO APP.CLINIC_USER_EXPERTISE (VET_CLINIC_USER_ID, EXPERTISES_EXPERTISE_ID)
VALUES ('1951', '17');
INSERT INTO APP.CLINIC_USER_EXPERTISE (VET_CLINIC_USER_ID, EXPERTISES_EXPERTISE_ID)
VALUES ('1951', '19');
INSERT INTO APP.CLINIC_USER_EXPERTISE (VET_CLINIC_USER_ID, EXPERTISES_EXPERTISE_ID)
VALUES ('2501', '18');
INSERT INTO APP.CLINIC_USER_EXPERTISE (VET_CLINIC_USER_ID, EXPERTISES_EXPERTISE_ID)
VALUES ('2501', '8');
INSERT INTO APP.CLINIC_USER_EXPERTISE (VET_CLINIC_USER_ID, EXPERTISES_EXPERTISE_ID)
VALUES ('2502', '15');
INSERT INTO APP.CLINIC_USER_EXPERTISE (VET_CLINIC_USER_ID, EXPERTISES_EXPERTISE_ID)
VALUES ('2502', '8');
INSERT INTO APP.CLINIC_USER_EXPERTISE (VET_CLINIC_USER_ID, EXPERTISES_EXPERTISE_ID)
VALUES ('2503', '13');
INSERT INTO APP.CLINIC_USER_EXPERTISE (VET_CLINIC_USER_ID, EXPERTISES_EXPERTISE_ID)
VALUES ('2503', '17');
INSERT INTO APP.CLINIC_USER_EXPERTISE (VET_CLINIC_USER_ID, EXPERTISES_EXPERTISE_ID)
VALUES ('2503', '20');
INSERT INTO APP.CLINIC_USER_EXPERTISE (VET_CLINIC_USER_ID, EXPERTISES_EXPERTISE_ID)
VALUES ('2504', '15');
INSERT INTO APP.CLINIC_USER_EXPERTISE (VET_CLINIC_USER_ID, EXPERTISES_EXPERTISE_ID)
VALUES ('2504', '17');
INSERT INTO APP.CLINIC_USER_EXPERTISE (VET_CLINIC_USER_ID, EXPERTISES_EXPERTISE_ID)
VALUES ('2504', '18');
INSERT INTO APP.CLINIC_USER_EXPERTISE (VET_CLINIC_USER_ID, EXPERTISES_EXPERTISE_ID)
VALUES ('2505', '10');
INSERT INTO APP.CLINIC_USER_EXPERTISE (VET_CLINIC_USER_ID, EXPERTISES_EXPERTISE_ID)
VALUES ('2505', '6');
INSERT INTO APP.CLINIC_USER_EXPERTISE (VET_CLINIC_USER_ID, EXPERTISES_EXPERTISE_ID)
VALUES ('2506', '14');
INSERT INTO APP.CLINIC_USER_EXPERTISE (VET_CLINIC_USER_ID, EXPERTISES_EXPERTISE_ID)
VALUES ('2506', '7');
