INSERT INTO expertise (EXPERTISE_ID, NAME)
VALUES ('1', 'Surgery'),
       ('2', 'Internal Medicine'),
       ('3', 'Radiology'),
       ('4', 'Cardiology'),
       ('5', 'Dermatology'),
       ('6', 'Oncology'),
       ('7', 'Ophthalmology'),
       ('8', 'Dentistry'),
       ('9', 'Neurology'),
       ('10', 'Orthopedics'),
       ('11', 'Nutrition'),
       ('12', 'Behavior'),
       ('13', 'Exotic Animal Medicine'),
       ('14', 'Avian Medicine'),
       ('15', 'Equine Medicine'),
       ('16', 'Livestock Medicine'),
       ('17', 'Anesthesiology'),
       ('18', 'Emergency and Critical Care'),
       ('19', 'Reproductive Medicine'),
       ('20', 'Pathology');
