INSERT INTO APP.PET (PET_ID, SPECIES, BREED, NAME, HEALTH_STATUS)
VALUES ('1', 'Dog', 'Labrador Retriever', 'Buddy', 'Healthy'),
       ('2', 'Cat', 'Persian', 'Whiskers', 'Sick'),
       ('3', 'Bird', 'Parakeet', 'Sunny', 'Dead'),
       ('4', 'Dog', 'Golden Retriever', 'Max', 'Recovering'),
       ('5', 'Cat', 'Siamese', 'Luna', 'Under Observation'),
       ('6', 'Bird', 'Canary', 'Tweetie', 'Critical Condition'),
       ('7', 'Dog', 'German Shepherd', 'Rocky', 'Healthy'),
       ('8', 'Cat', 'Maine Coon', 'Simba', 'Sick'),
       ('9', 'Bird', 'Cockatiel', 'Peaches', 'Dead'),
       ('10', 'Dog', 'Beagle', 'Bailey', 'Recovering'),
       ('11', 'Cat', 'Bengal', 'Tiger', 'Under Observation'),
       ('12', 'Bird', 'Lovebird', 'Kiwi', 'Critical Condition'),
       ('13', 'Dog', 'Dachshund', 'Charlie', 'Healthy'),
       ('14', 'Cat', 'Ragdoll', 'Milo', 'Sick'),
       ('15', 'Bird', 'Finch', 'Sky', 'Dead'),
       ('16', 'Dog', 'Boxer', 'Duke', 'Recovering'),
       ('17', 'Cat', 'Scottish Fold', 'Oreo', 'Under Observation'),
       ('18', 'Bird', 'Parrot', 'Polly', 'Critical Condition'),
       ('19', 'Dog', 'Poodle', 'Teddy', 'Healthy'),
       ('20', 'Cat', 'Sphynx', 'Cleo', 'Sick'),
       ('21', 'Bird', 'Budgerigar', 'Blue', 'Dead'),
       ('22', 'Dog', 'Shih Tzu', 'Toby', 'Recovering'),
       ('23', 'Cat', 'Russian Blue', 'Misty', 'Under Observation'),
       ('24', 'Bird', 'Cockatoo', 'Rainbow', 'Critical Condition'),
       ('25', 'Dog', 'Siberian Husky', 'Luna', 'Healthy'),
       ('26', 'Cat', 'Tabby', 'Mittens', 'Sick'),
       ('27', 'Bird', 'African Grey Parrot', 'Echo', 'Dead'),
       ('28', 'Dog', 'Rottweiler', 'Max', 'Recovering'),
       ('29', 'Cat', 'Calico', 'Whiskers', 'Under Observation'),
       ('30', 'Bird', 'Macaw', 'Rio', 'Critical Condition'),
       ('31', 'Dog', 'Border Collie', 'Charlie', 'Healthy'),
       ('32', 'Cat', 'American Shorthair', 'Loki', 'Sick'),
       ('33', 'Bird', 'Cockatiel', 'Sunny', 'Dead'),
       ('34', 'Dog', 'Chihuahua', 'Bella', 'Recovering'),
       ('35', 'Cat', 'Exotic Shorthair', 'Smokey', 'Under Observation'),
       ('36', 'Bird', 'Canary', 'Sunny', 'Critical Condition'),
       ('37', 'Dog', 'Great Dane', 'Thor', 'Healthy'),
       ('38', 'Cat', 'Himalayan', 'Snowball', 'Sick'),
       ('39', 'Bird', 'Parakeet', 'Kiwi', 'Dead'),
       ('40', 'Dog', 'Pug', 'Max', 'Recovering'),
       ('41', 'Cat', 'Persian', 'Fluffy', 'Under Observation'),
       ('42', 'Bird', 'Budgerigar', 'Buddy', 'Critical Condition'),
       ('43', 'Dog', 'Maltese', 'Buddy', 'Healthy'),
       ('44', 'Cat', 'British Shorthair', 'Oliver', 'Sick'),
       ('45', 'Bird', 'Finch', 'Chirpy', 'Dead'),
       ('46', 'Dog', 'Shiba Inu', 'Hachi', 'Recovering'),
       ('47', 'Cat', 'Birman', 'Angel', 'Under Observation'),
       ('48', 'Bird', 'Lovebird', 'Tweety', 'Critical Condition'),
       ('49', 'Dog', 'Cocker Spaniel', 'Bella', 'Healthy'),
       ('50', 'Cat', 'Cornish Rex', 'Tigger', 'Sick');
