CREATE TABLE CLINIC_USER
(
    CLINIC_USER_ID VARCHAR(10) NOT NULL,
    USER_ROLE      VARCHAR(15),
    EMAIL          VARCHAR(255) UNIQUE,
    PASSWORD       VARCHAR(255),
    PRIMARY KEY (CLINIC_USER_ID)
);
