CREATE TABLE CUSTOMER
(
    CUSTOMER_ID   VARCHAR(10) NOT NULL,
    ADDRESS       VARCHAR(255),
    EMAIL         VARCHAR(255),
    FULL_NAME     VARCHAR(100),
    DATE_OF_BIRTH VARCHAR(10),
    PHONE_NUMBER  VARCHAR(13),
    GENDER        VARCHAR(6),
    PRIMARY KEY (CUSTOMER_ID)
);
