CREATE TABLE PET
(
    PET_ID        VARCHAR(10) NOT NULL,
    BREED         VARCHAR(255),
    HEALTH_STATUS VARCHAR(50),
    "NAME"        VARCHAR(255),
    SPECIES       VARCHAR(255),
    CUSTOMER_ID   VARCHAR(10),
    PRIMARY KEY (PET_ID),
    CONSTRAINT FK_CUSTOMER FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER (CUSTOMER_ID)
);
