CREATE TABLE PET
(
    PET_ID        VARCHAR(10) NOT NULL,
    BREED         VARCHAR(255),
    HEALTH_STATUS VARCHAR(50),
    "NAME"        VARCHAR(255),
    SPECIES       VARCHAR(255),
    PRIMARY KEY (PET_ID)
);
